### ISSUE TITLE
Release v0.0.4?

### ISSUE THREAD

**Issue by kpelzel** [DataWorkflowServices/dws-slurm-bb-plugin#55]
Would it be possible to release v0.0.4? I want to provide [these instructions](https://dataworkflowservices.github.io/v0.0.3/guides/dws-on-csm/readme) to our team, but I need the changes from [this PR](https://github.com/DataWorkflowServices/dws-slurm-bb-plugin/pull/53) in a tagged release for easier guidance.

**Comment by roehrich-hpe** [comment]
Sure, I'll work on that.  There are some changes to DWS that you'll have to adapt your code to handle, but it should be small stuff.

**Comment by roehrich-hpe** [comment]
Released v0.0.5.
